#!/bin/bash

function displayHelp()
{
    echo "Syntax: dockerRunOpenhab2 <u|r> <e>"
    echo "                      - u: Ubuntu environment"
    echo "                      - r: Raspbian environment"
    echo "                      - e: Setup environment"
    exit
}

function runScript()
{
    local scriptDir=${TMA_SO_HOME}/sources/scripts
    local buildDir=${scriptDir}/${1}
    
    local DOCKER_DATA_DIR=${TMA_SO_HOME}/dockerdatadir
    local OH2_DATA_DIR=${DOCKER_DATA_DIR}/openhab2

    # Check & create dockerdatadir root folder
    if [ ! -d "${DOCKER_DATA_DIR}" ]; then
        echo 'Creating ${DOCKER_DATA_DIR} to store OpenHab2 Data...'
        mkdir -m 777 ${DOCKER_DATA_DIR}
    fi
    # Check & create dockerdir-openhab2 root folder
    if [ ! -d "${OH2_DATA_DIR}" ]; then
        echo 'Creating ${OH2_DATA_DIR} to store OpenHab2 Data...'
        mkdir -m 777 ${OH2_DATA_DIR}
    fi
    # Check & copy openhab2 configuration
    if [ ! -d "${OH2_DATA_DIR}/conf" ]; then
        cp -rf ${TMA_SO_HOME}/sources/openhab2-configurations/* ${OH2_DATA_DIR}/
        chmod -R 777 ${OH2_DATA_DIR}/*
    fi

    if [ -z "${2}" ]; then
        docker run -d -p 8080:8080 -p 8443:8443 \
            -v ${TMA_SO_HOME}/dockerdatadir/openhab2/conf:/usr/openhab-2.0/conf \
            -v ${TMA_SO_HOME}/dockerdatadir/openhab2/addons:/usr/openhab-2.0/addons \
            -v ${TMA_SO_HOME}/dockerdatadir/openhab2/userdata:/usr/openhab-2.0/userdata \
            -v ${TMA_SO_HOME}/dockerdatadir/openhab2/runtime/etc:/usr/openhab-2.0/runtime/etc \
            -v ${TMA_SO_HOME}/dockerdatadir/openhab2/runtime/karaf/etc:/usr/openhab-2.0/runtime/karaf/etc \
            --name openhab2 scripts_openhab:latest
    fi
}

function entryPoint()
{
    if [ "$1" == "u" ]; then
        runScript "ubuntu" "$2"
    elif [ "$1" == "ubuntu" ]; then
        runScript "ubuntu" "$2"
    elif [ "$1" == "r" ]; then
        runScript "raspbian" "$2"
    elif [ "$1" == "raspbian" ]; then
        runScript "raspbian" "$2"
    elif [ "$1" == "e" ]; then
        runScript "${TMA_SO_TARGET_OS}" "e"
    else
        displayHelp
    fi
}


if [ -z "${TMA_SO_HOME}" ]; then
    echo "Please set ENV Variable TMA_SO_HOME pointing to TMA_SO repository"
    exit
fi

if [ -z "${TMA_SO_TARGET_OS}" ]; then
    echo "Please set ENV Variable TMA_SO_TARGET_OS=<ubuntu | raspbian>"
    exit
fi

ARG1=""
ARG2=""
if [ ! -z "${2}" ]; then
    echo "Prepare to setup environment for dockerOpenhab2"
    ARG2=${2}
fi

if [ -z "${1}" ]; then
    ARG1=${TMA_SO_TARGET_OS}
else
    ARG1=${1}
fi


entryPoint "${ARG1}" "${ARG2}"