version: '2'
services:
  openhab:
    build: ${TMA_SO_HOME}/sources/scripts/${TMA_SO_TARGET_OS}/docker-openhab
    ports:
     - "8080:8080"
     - "8443:8443"
    volumes:
     - ${TMA_SO_OPENHAB_CONFIG}/conf:/usr/openhab-2.0/conf
     - ${TMA_SO_OPENHAB_CONFIG}/addons:/usr/openhab-2.0/addons
     - ${TMA_SO_OPENHAB_CONFIG}/userdata:/usr/openhab-2.0/userdata
     - ${TMA_SO_OPENHAB_CONFIG}/runtime/etc:/usr/openhab-2.0/runtime/etc
     - ${TMA_SO_OPENHAB_CONFIG}/runtime/karaf/etc:/usr/openhab-2.0/runtime/karaf/etc

