#!/bin/bash

function displayHelp()
{
    echo "Syntax: deployOpenhabConfig <u|r>"
    echo "                      - u: Ubuntu environment"
    echo "                      - r: Raspbian environment"
    exit
}

function runScript()
{
    local scriptDir=${TMA_SO_HOME}/sources/scripts
    local buildDir=${scriptDir}/${1}
    
    local DOCKER_DATA_DIR=${TMA_SO_HOME}/dockerdatadir
    local OH2_DATA_DIR=${DOCKER_DATA_DIR}/openhab2

    # Check & create dockerdatadir root folder
    if [ ! -d "${DOCKER_DATA_DIR}" ]; then
        echo 'Creating ${DOCKER_DATA_DIR} to store OpenHab2 Data...'
        mkdir -m 777 ${DOCKER_DATA_DIR}
    fi
    # Check & create dockerdir-openhab2 root folder
    if [ ! -d "${OH2_DATA_DIR}" ]; then
        echo 'Creating ${OH2_DATA_DIR} to store OpenHab2 Data...'
        mkdir -m 777 ${OH2_DATA_DIR}
    fi
    # Check & copy openhab2 configuration

    cp -rvf ${TMA_SO_HOME}/sources/openhab2-configurations/conf ${OH2_DATA_DIR}/
}

function entryPoint()
{
    if [ "$1" == "u" ]; then
        runScript "ubuntu"
    elif [ "$1" == "ubuntu" ]; then
        runScript "ubuntu"
    elif [ "$1" == "r" ]; then
        runScript "raspbian"
    elif [ "$1" == "raspbian" ]; then
        runScript "raspbian"
    elif [ "$1" == "-h" ]; then
        displayHelp
    else
        displayHelp
    fi
}


if [ -z "${TMA_SO_HOME}" ]; then
    echo "Please set ENV Variable TMA_SO_HOME pointing to TMA_SO repository"
    exit
fi
if [ -z "${TMA_SO_TARGET_OS}" ]; then
    echo "Please set ENV Variable TMA_SO_TARGET_OS=<ubuntu | raspbian>"
    exit
fi


ARG1=""
if [ -z "${1}" ]; then
    ARG1=${TMA_SO_TARGET_OS}
fi

entryPoint "$ARG1"