#!/bin/bash

function displayHelp()
{
    echo "Syntax: dockerRunMQTT <u|r> <e>"
    echo "                      - u: Ubuntu environment"
    echo "                      - r: Raspbian environment"
    echo "                      - e: Setup environment"
    exit
}

function runScript()
{
    local scriptDir=${TMA_SO_HOME}/sources/scripts
    local buildDir=${scriptDir}/${1}
    
    local DOCKER_DATA_DIR=${TMA_SO_HOME}/dockerdatadir
    local MQTT_DATA_DIR=${DOCKER_DATA_DIR}/mqtt
    
    if [ ! -d "${DOCKER_DATA_DIR}" ]; then
        echo 'Creating ${DOCKER_DATA_DIR} to store MQTT Data...'
        mkdir -m 777 ${DOCKER_DATA_DIR}
    fi

    if [ ! -d "${MQTT_DATA_DIR}" ]; then
        echo 'Creating ${MQTT_DATA_DIR} to store MQTT Data...'
        mkdir -m 777 ${MQTT_DATA_DIR} ${MQTT_DATA_DIR}/config ${MQTT_DATA_DIR}/log ${MQTT_DATA_DIR}/data
    fi

    if [ ! -d "${MQTT_DATA_DIR}/config/mosquitto.conf" ]; then
        cp -rf ${buildDir}/docker-mosquitto/config/* ${MQTT_DATA_DIR}/config
        chmod 777 ${MQTT_DATA_DIR}/config
        chmod 777 ${MQTT_DATA_DIR}/config/*
    fi


    if [ -z "${2}" ]; then
        echo "Running docker images toke/mosquitto"
        docker run -d -p 1883:1883 -p 9001:9001 \
                -v ${TMA_SO_HOME}/dockerdatadir/mqtt/config:/mqtt/config:ro \
                -v ${TMA_SO_HOME}/dockerdatadir/mqtt/log:/mqtt/log \
                -v ${TMA_SO_HOME}/dockerdatadir/mqtt/data/:/mqtt/data/ \
                --name mqtt toke/mosquitto
    fi
}

function entryPoint()
{
    if [ "$1" == "u" ]; then
        runScript "ubuntu" "$2"
    elif [ "$1" == "ubuntu" ]; then
        runScript "ubuntu" "$2"
    elif [ "$1" == "r" ]; then
        runScript "raspbian" "$2"
    elif [ "$1" == "raspbian" ]; then
        runScript "raspbian" "$2"
    elif [ "$1" == "e" ]; then
        runScript "${TMA_SO_TARGET_OS}" "e"
    else
        displayHelp
    fi
}


if [ -z "${TMA_SO_HOME}" ]; then
    echo "Please set ENV Variable TMA_SO_HOME pointing to TMA_SO repository"
    exit
fi


ARG1=""
ARG2=""
if [ ! -z "${2}" ]; then
    echo "Prepare to setup environment for dockerMQTT"
    ARG2=${2}
fi

if [ -z "${1}" ]; then
    if [ -z "${TMA_SO_TARGET_OS}" ]; then
        echo "Please set ENV Variable TMA_SO_TARGET_OS=<ubuntu | raspbian>"
        exit
    fi
    ARG1=${TMA_SO_TARGET_OS}
else
    ARG1=${1}
fi

entryPoint "${ARG1}" "${ARG2}"
